from fastapi import FastAPI
from src.utils.db import Base, engine
from src.tasks.routers.task_router import task_router
from src.user.router import user_router


# 🔥 Example Final Enterprise Structure
# src/
# │
# ├── tasks/
# ├── users/
# ├── auth/
# ├── config/
# ├── middleware/
# ├── utils/
# ├── exceptions/
# ├── database/
# ├── tests/

# 🔥 __init__.py is used to make a directory behave like a Python package.
    # It helps Python recognize folder imports properly.

    # why we use:
    # With __init__.py:

    # Python treats folder as package
    # imports work correctly
    # modular architecture supported

#  🔥__pycache__ stores compiled bytecode .pyc files generated by Python for faster execution
    # When Python runs:
    # main.py

    # it compiles source code into bytecode:
    # .pyc
    # and stores inside:
    # __pycache__/
    # This improves:

    # performance
    # faster module loading

# Creates all database tables in PostgreSQL based on SQLAlchemy models
# If tables already exist, it will not recreate them
Base.metadata.create_all(engine)

# Initializes FastAPI application instance
app = FastAPI()

# Registers all task-related API routes/endpoints with FastAPI application
app.include_router(task_router)

# Registers all user-related API routes/endpoints with FastAPI application
app.include_router(user_router)
